version: '3'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=K8qUYs4h
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: on-failure
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "docker/wait-for-it.sh db:5432 -- python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    restart: on-failure
